apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testresource.qibobo.com
spec:
  group: qibobo.com
  version: v1beta1
  names:
    kind: TestResource
    plural: testresources
  scope: Namespaced